### ISSUE TITLE
mac os is not avaiable

### ISSUE THREAD

**Issue by claywong** [XGilmar/JetBrains-reset-trial-app#1]

**Comment by XGilmar** [comment]
Previously it was not available for the MacOS environment. Verify now the new changes and check that everything works.

**Comment by rohanshah000x7** [comment]
`macOS Sonoma 14.1` works like a charm, thanks

**Comment by hmtanbir** [comment]
@rohanshah000x7 How can I install in macOS Sonoma 14.1 ?
cc: @XGilmar
