### ISSUE TITLE
not working for goland 2024.2.3

### ISSUE THREAD

**Issue by akrikheli** [XGilmar/JetBrains-reset-trial-app#10]
not working for goland 2024.2.3

**Comment by rawr-code** [comment]
not working for WebStorm 2024.2.2

https://github.com/user-attachments/assets/416b7b41-c5d0-4417-8fe7-f484a2b13065

**Comment by leek231** [comment]
@rawr-code change path for other.xml, maybe this file in other location

**Comment by rawr-code** [comment]
> @rawr-code change path for other.xml, maybe this file in other location

Bash script saved to: /Users/rawrcode/Projects/intel/JetBrains-reset-trial-app/reset_script.sh
sed: /Users/rawrcode/Library/Preferences/WebStorm2024.2/options/other.xml: No such file or directory
rm: /Users/rawrcode/Library/Preferences/com.apple.java.util.prefs.plist: No such file or directory
rm: /Users/rawrcode/Library/Preferences/com.jetbrains.*.plist: No such file or directory
rm: /Users/rawrcode/Library/Preferences/jetbrains.*.*.plist: No such file or directory
[ INFO ] Resetting period for WebStorm2024.2
Removing evaluation key...
[ OK ] Key removed successfully.
[ OK ] Latest version removed successfully.
Removing evlsprt in options.xml...
[ ERROR ] Failed to remove evlsprt.
[ OK ] Latest evlsprt removed successfully.
[ INFO ] removing additional plist files...
[ INFO ] Removing com.apple.java.util.prefs.plist...
[ ERROR ] Failed to remove com.apple.java.util.prefs.plist.
[ INFO ] Removing com.jetbrains.*.plist...
[ ERROR ] Failed to remove com.jetbrains.*.plist.
[ INFO ] Removing jetbrains.*.*.plist...
[ ERROR ] Failed to remove jetbrains.*.*.plist.

**Comment by DanielOberlechner** [comment]
@people here,
we fixed a issue with the macOS script and released a new version (trials-app-1.1) and now it should work again.

Greets Daniel
