### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ShadowOfHeaven-Me** [XGilmar/JetBrains-reset-trial-app#2]
![image](https://github.com/user-attachments/assets/0d245da9-ce8e-4929-9a86-41bcdc4dc3a3)
I'm using IntelliJ Ultimate. I used up the trial about a month ago, and currentlly I have 3 intellijs downloaded: 2 community editions and 1 ultimate.
![image](https://github.com/user-attachments/assets/ee386094-38ae-43f4-92b0-f5626b2c955c)
This is always what shows up

**Comment by ShadowOfHeaven-Me** [comment]
I should mention that the "start" doesn't change anything visually, and nothing can be clicked in the gui

**Comment by XGilmar** [comment]
> I should mention that the "start" doesn't change anything visually, and nothing can be clicked in the gui

Can you run the application with administrator permissions and send a screenshot of the logs it shows you when you start it?

![image](https://github.com/user-attachments/assets/47206b39-b312-433e-a0d5-442bc0556940)

**Comment by ShadowOfHeaven-Me** [comment]
Running as administrator fixed it, thank you.
![image](https://github.com/user-attachments/assets/aa4e603f-7814-45b9-b188-5b2ed1efc941)
You should add some kind of text that displays: "This file must be ran as an Administrator"
