### ISSUE TITLE
Java Application launch failed

### ISSUE THREAD

**Issue by Yukiiilove123** [XGilmar/JetBrains-reset-trial-app#3]
Hi. I'm getting this error when I try to run it: 
<img width="1440" alt="Screenshot 2024-07-18 at 1 46 55 AM" src="https://github.com/user-attachments/assets/251bff69-3495-4989-aca1-ee120e5d0ecf">
What should I do??

**Comment by XGilmar** [comment]
> Hi. I'm getting this error when I try to run it: <img alt="Screenshot 2024-07-18 at 1 46 55 AM" width="1440" src="https://private-user-images.githubusercontent.com/143915958/349666861-251bff69-3495-4989-aca1-ee120e5d0ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNDk1OTQsIm5iZiI6MTcyMTI0OTI5NCwicGF0aCI6Ii8xNDM5MTU5NTgvMzQ5NjY2ODYxLTI1MWJmZjY5LTM0OTUtNDk4OS1hY2ExLWVlMTIwZTVkMGVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMDQ4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzYyZjNmYzc0MjU2OWUzOWVjNTI4MGEwYmJjODc1ZDBkOTk3NmQ5NzRkNjU2ZWE2ZmM3ZmVjNjQxNjk4NWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dukyrY2kVvpMd5DlIMBNTN0IzPBGFCRMy9c19VHq7yU"> What should I do??

Hi, can you tell me how you are running the application? If you try to open the application directly remember that you must have your environment configured with Java on Mac so that it can be detected. Please share more information.

**Comment by Yukiiilove123** [comment]
Sure I Have Java installed on my mac and updated it but the problem didn't get resolved

**Comment by XGilmar** [comment]
> Sure I Have Java installed on my mac and updated it but the problem didn't get resolved

Ok, you can open your terminal and display the Java version with the command ```java -version```

**Comment by Yukiiilove123** [comment]
Thanks It worked!

**Comment by XGilmar** [comment]
> Gracias.

I hope I can help you Nithya!
