### ISSUE TITLE
Does not work om mac for latest Rider version

### ISSUE THREAD

**Issue by JasperFioole21** [XGilmar/JetBrains-reset-trial-app#4]
What versions does this app support?

I was not able to reset the latest rider version.

**Comment by XGilmar** [comment]
> What versions does this app support?
> 
> I was not able to reset the latest rider version.

There was some indicator where rider could not be reset. Can you try running the application with permissions and show me what happens?

**Comment by JasperFioole21** [comment]
<img width="512" alt="Scherm­afbeelding 2024-07-22 om 21 54 19" src="https://github.com/user-attachments/assets/4fc9d170-c55d-489a-8645-c4a3bd6ec6a7">

The tool does work but it tells me the file does not exist.

**Comment by xurpax** [comment]
> <img alt="Scherm­afbeelding 2024-07-22 om 21 54 19" width="512" src="https://private-user-images.githubusercontent.com/5971671/351095879-4fc9d170-c55d-489a-8645-c4a3bd6ec6a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjM3NDgsIm5iZiI6MTcyMTcyMzQ0OCwicGF0aCI6Ii81OTcxNjcxLzM1MTA5NTg3OS00ZmM5ZDE3MC1jNTVkLTQ4OWEtODY0NS1jNGEzYmQ2ZWM2YTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDgzMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZmOGFiY2IyNTI3MDY4NWI1MTYxMzMyZmEzMTRmMTg4MzU0NjY1OGJhNjVlY2EwZDAxYjA5ZjMxYTRmOWNmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iTopwEqgjXSfH0xg17i20bd-waorjGbj52qoppZUkZc">
> The tool does work but it tells me the file does not exist.

I got the same error message. I was trying to reset IntelliJ Idea on MacOS Sonoma 14.5

**Comment by JasperFioole21** [comment]
Maybe they changed a few things in the newest version. I’m not sure what version will still work.

**Comment by XGilmar** [comment]
> Maybe they changed a few things in the newest version. I’m not sure what version will still work.

I am using version 2024.1.1 of Intellij and 2024.1.3 of DataGrip. Can you revert to one of those versions in your IDE and check that it works?

**Comment by JasperFioole21** [comment]
I did not try another version.

I did find out that this file is working: https://gist.githubusercontent.com/patchthecode/6eeeea214540bb735bd54548ead4b85f/raw/38e9cd6feb8dc7f43967058740a8b6ac83c7c796/reset_idea_trial.sh

It probably has something to do with options.xml

**Comment by XGilmar** [comment]
> I did not try another version.
> 
> I did find out that this file is working: https://gist.githubusercontent.com/patchthecode/6eeeea214540bb735bd54548ead4b85f/raw/38e9cd6feb8dc7f43967058740a8b6ac83c7c796/reset_idea_trial.sh
> 
> It probably has something to do with options.xml

Ok, in the next hours I will make an adjustment to make it work.

**Comment by Blockost** [comment]
> I did not try another version.
> 
> I did find out that this file is working: https://gist.githubusercontent.com/patchthecode/6eeeea214540bb735bd54548ead4b85f/raw/38e9cd6feb8dc7f43967058740a8b6ac83c7c796/reset_idea_trial.sh
> 
> It probably has something to do with options.xml

Can confirm that the script just worked for `JetBrains Rider 2024.2.6` but the tool didn't
