### ISSUE TITLE
Doesn't find CLion on Arch Linux

### ISSUE THREAD

**Issue by KeksNino** [XGilmar/JetBrains-reset-trial-app#5]
I installed CLion through flatpak on Arch Linux and the reset trial doesnt find it. Can i set it manually?

**Comment by XGilmar** [comment]
> I installed CLion through flatpak on Arch Linux and the reset trial doesnt find it. Can i set it manually?

You can search for the path generated by CLion and delete what is needed as I do in the script. https://github.com/XGilmar/JetBrains-reset-trial-app/blob/b9a25a810b65ff1e6ef8a4c3e8a5b528ff0ab8c0/src/main/java/com/dev/reset/trial/app/models/LinuxProduct.java#L45 I download the products directly from the jetbrains page as they do not take long to update.
