### ISSUE TITLE
Not working in Intellij 2024.01

### ISSUE THREAD

**Issue by AhmedHisham99** [XGilmar/JetBrains-reset-trial-app#7]
It only works in first time after that not working.
<img width="358" alt="Screenshot 2024-08-31 at 1 17 28 PM" src="https://github.com/user-attachments/assets/ba66230b-e1e3-4bb8-8bdf-80d91404ef03">

**Comment by AhmedHisham99** [comment]
<img width="402" alt="Screenshot 2024-08-31 at 1 18 47 PM" src="https://github.com/user-attachments/assets/ec75de5f-ab8f-48d2-8235-e76e232668eb">

**Comment by Dark-Tower-Coder** [comment]
It doesn't work for me either.
version 2024.1.4
also run with root rights, no change.

**Comment by NavSinghCS** [comment]
it is not even working for me
version 2024.2.2 
nothing happens when click on the start buttons.

**Comment by DanielOberlechner** [comment]
@people here,
we fixed a issue with the macOS script and released a new version (trials-app-1.1) and now it should work again.

Greets Daniel
